<?php $addGameController = new AddGameController() ?>

<?php if(!$session->checkAuthentication()):?>
    <?php header('Location: index.php') ?>
<?php endif ?>

<?php if(isset($_POST['gametitle'])): ?>
    <!-- Lancement de la fonction d'ajout de jeu-->
    <?= $addGameController->addNewGame($_POST) ?>
<?php endif ?>

<section class='add'>
    <h2>Ajout d'un jeu</h2>
    <form action="index.php?p=add" name="addgame" id="addgame" method="POST" enctype="multipart/form-data">
        <ul>
            <li>
                <label for="gametitle">Titre du jeu:</label>
                <input name="gametitle" type='text' id="gametitle" onblur="checkForm(this)">
            </li>  
            <?php $developpers = $addGameController->getDevs() ?>
            <li>
                <p class="hidden errormsg">Vous devez obligatoirement choisir un developpeur</p>
                <label for="dev">Developpeur:</label>
                <select name="dev">
                    <option value="0">--Choisissez un Developpeur--</option>
                    <?php foreach ($developpers as $developper):?>
                        <option id="<?= intval($developper['id']) ?>" value="<?= intval($developper['id']) ?>"><?= $developper['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <?php $editors = $addGameController->getEditors() ?>
            <li>
                <p class="hidden errormsg">Vous devez obligatoirement choisir un editeur</p>
                <label for="editor">Editeur:</label>
                <select name="editor" >
                    <option value="0">--Choisissez un Editeur--</option>
                    <?php foreach ($editors as $editor):?>
                        <option id="<?= intval($editor['id']) ?>" value="<?= intval($editor['id']) ?>"><?= $editor['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li> 
            <li>
                <label for="releasedate">Année de parution</label>
                <input type="text" id="releasedate" name="releasedate" maxlength="4" onblur="checkForm(this)">
            </li> 
            <?php $platforms = $addGameController->getPlatforms() ?>
            <li>
                <label for="platform1">Plateformes:</label>
                <div>
                    <i id="addplatform" class="fas fa-plus moreinput"></i>
                    <i id="removeplatform" class="fas fa-minus lessinput disabled"></i>
                </div>
                <select name="platform1">
                    <option value="0">--Choisissez une plateforme--</option>
                    <?php foreach ($platforms as $platform):?>
                        <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"><?= $platform['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="platform2" class="hidden">
                <select name="platform2" id="platformselect2">
                    <option value="0">--Choisissez une plateforme--</option>
                    <?php foreach ($platforms as $platform):?>
                        <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"><?= $platform['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="platform3" class="hidden">
                <select name="platform3" id="platformselect3">
                    <option value="0">--Choisissez une plateforme--</option>                
                    <?php foreach ($platforms as $platform):?>
                        <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"><?= $platform['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="platform4" class="hidden">
                <select name="platform4" id="platformselect4">
                    <option value="0">--Choisissez une plateforme--</option>
                    <?php foreach ($platforms as $platform):?>
                        <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"><?= $platform['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="platform5" class="hidden">
                <select name="platform5" id="platformselect5">
                    <option value="0">--Choisissez une plateforme--</option>
                    <?php foreach ($platforms as $platform):?>
                        <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"><?= $platform['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="platform6" class="hidden">
                <select name="platform6" id="platformselect6">
                    <option value="0">--Choisissez une plateforme--</option>
                    <?php foreach ($platforms as $platform):?>
                        <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"><?= $platform['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <?php $genres = $addGameController->getGenres() ?>
            <li>
                <label for="genre1">Genres:</label>
                <div>
                    <i id="addgenre" class="fas fa-plus moreinput"></i>
                    <i id="removegenre" class="fas fa-minus lessinput disabled"></i>
                </div>
                <select name="genre1">
                    <option value="0">--Choisissez un genre--</option>
                    <?php foreach ($genres as $genre):?>
                        <option id="<?= intval($genre['id']) ?>" value="<?= intval($genre['id']) ?>"><?= $genre['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="genre2" class="hidden">
                <select name="genre2" id="genreselect2">
                <option value="0">--Choisissez un genre--</option>
                    <?php foreach ($genres as $genre):?>
                        <option id="<?= intval($genre['id']) ?>" value="<?= intval($genre['id']) ?>"><?= $genre['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="genre3" class="hidden">
                <select name="genre3" id="genreselect3">
                <option value="0">--Choisissez un genre--</option>
                    <?php foreach ($genres as $genre):?>
                        <option id="<?= intval($genre['id']) ?>" value="<?= intval($genre['id']) ?>"><?= $genre['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li>
                <label for="picture">Photo du jeu:</label>
                <img src="public/img/games/defaultgame.png" class='imgpreview' >
                <input type="file" id="picture" name="picture" accept=".jpg,.png" onchange="imagePreview(event)">
            </li>  
            <li>
                <label for='description'>Description:</label>
                <textarea name='description' cols="20" rows="15"></textarea>
            </li>
        </ul>
        <button type="submit" id="addBtn" >Enregistrer</button>
        <button type="reset" id="resetbtn">Annuler</button>
    </form>
</section>