<form action="index.php?p=admin&list=platform" name="addelement" class="addelement" method="POST" enctype="multipart/form-data">
    <h3>Ajouter une Plateforme:</h3>
    <label for="addplatformname">Nom</label>
    <input type="text" name="addplatformname">
    <label for="addplatformdate">Année de sortie</label>
    <input type="text" name="addplatformdate">
    <button type="submit">Ajouter</button>
</form>

<table id="admingenre">
    <thead>
        <tr>
            <th>Nom</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($adminLists as $adminList): ?>
            <tr>
                <td><a href="index.php?p=all&platformfilter=<?= $adminList['id'] ?>"><?= $adminList['name'] ?></a></td>
                <td><a href="index.php?p=admin&action=delgame&id=<?=$adminList['id'] ?>&list=platform"><i class="fas fa-times"></i></a></td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>