<form action="index.php?p=admin&list=platform" name="addelement" class="addelement" method="POST" enctype="multipart/form-data">
    <h3>Ajouter une Plateforme:</h3>
    <label for="addplatformname">Nom</label>
    <input type="text" name="addplatformname">
    <label for="addplatformdate">Année de sortie</label>
    <input type="text" name="addplatformdate">
    <button type="submit">Ajouter</button>
</form>

<table id="adminplatform">
</table>