<?php $allGameController = new AllGameController() ?> 
<!-- Détermination de la page actuelle -->
<?php if(!empty($_GET['page'])) : ?>
    <?php $page = $_GET['page'] ?>
<?php else : ?>
     <?php $page = 1 ?>
<?php endif ?>

<?php $genreFilter = 0 ?>
<?php $platformFilter = 0 ?>
<?php $devFilter = 0 ?>
<?php $editorFilter = 0 ?>
<?php $wordFilter = "" ?>
<?php $orderFilter = "alphabeticalasc" ?>
<?php $letterFilter = "" ?>


    <!-- ------Verification des filtre de recherche------  -->

    <!-- filtre du champs de recherche -->
    <?php if (isset($_POST['search'])): ?>
        <?php $wordFilter = $_POST['search'] ?>
    <?php elseif (isset($_GET['search'])): ?>
        <?php $wordFilter = $_GET['search'] ?>
    <?php endif ?>
    <!-- filtre de genre -->
    <?php if (isset($_POST['genrefilter'])): ?>
        <?php $genreFilter = $_POST['genrefilter'] ?>
    <?php elseif (isset($_GET['genrefilter'])): ?>
        <?php $genreFilter = $_GET['genrefilter'] ?>
    <?php endif ?>
    <!-- filtre de plateforme -->
    <?php if (isset($_POST['platformfilter'])): ?>
        <?php $platformFilter = $_POST['platformfilter'] ?>
    <?php elseif (isset($_GET['platformfilter'])): ?>
        <?php $platformFilter = $_GET['platformfilter'] ?>
    <?php endif ?>
    <!-- filtre de dev -->
    <?php if (isset($_POST['devfilter'])): ?>
        <?php $devFilter = $_POST['devfilter'] ?>
    <?php elseif (isset($_GET['devfilter'])): ?>
        <?php $devFilter = $_GET['devfilter'] ?>
    <?php endif ?>
    <!-- filtre de dev -->
    <?php if (isset($_POST['editorfilter'])): ?>
        <?php $editorFilter = $_POST['editorfilter'] ?>
    <?php elseif (isset($_GET['editorfilter'])): ?>
        <?php $editorFilter = $_GET['editorfilter'] ?>
    <?php endif ?>
    <!-- ordre de tri -->
    <?php if (isset($_POST['orderfilter'])): ?>
        <?php $orderFilter = $_POST['orderfilter'] ?>
    <?php elseif (isset($_GET['orderfilter'])): ?>
        <?php $orderFilter = $_GET['orderfilter'] ?>
    <?php endif ?>
    <!-- filtre de tri par lettre -->
    <?php if (isset($_GET['letterfilter'])): ?>
        <?php $letterFilter = $_GET['letterfilter'] ?>
    <?php endif ?>

<!-- récupération des jeux selon les filtres -->
<?php $games = $allGameController->getGames() ?>
<?php $toPassList = $games ?>
<!-- récupération du nombre de pages pour la pagination -->
<?php  $nbPage = $allGameController->getPageNumbers() ?>

<section id="filter">
    <h3>Filtres de recherche:</h3>
    <form name="filterform" action='index.php?p=all' id="filterform" method="POST" >
        <div>
            <label for="search">Titre d'un jeu:</label>
            <input type="text" name="search">
        </div>
        <?php $genres = $allGameController->getGenres() ?>
        <div>
            <label for='genrefilter'>Genre:</label>
            <select name="genrefilter">
                <option value="0">--Choisissez un genre--</option>
                <?php foreach ($genres as $genre):?>
                    <option id="<?= intval($genre['id']) ?>" value="<?= intval($genre['id']) ?>"><?= $genre['name'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
        <?php $platforms = $allGameController->getPlatforms() ?>
        <div>
            <label for="platformfilter">Plateformes:</label>
            <select name="platformfilter">
                <option value="0">--Choisissez une plateforme--</option>
                <?php foreach ($platforms as $platform):?>
                    <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"><?= $platform['name'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
        <?php $developpers = $allGameController->getDevs() ?>
        <div>
            <label for="devfilter">Developpeur:</label>
            <select name="devfilter">
                <option value="0">--Choisissez un Developpeur--</option>
                <?php foreach ($developpers as $developper):?>
                    <option id="<?= intval($developper['id']) ?>" value="<?= intval($developper['id']) ?>"><?= $developper['name'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
        <?php $editors = $allGameController->getEditors() ?>
        <div>
            <p class="hidden errormsg">Vous devez obligatoirement choisir un editeur</p>
            <label for="editor">Editeur:</label>
            <select name="editorfilter">
                <option value="0">--Choisissez un Editeur--</option>
                <?php foreach ($editors as $editor):?>
                    <option id="<?= intval($editor['id']) ?>" value="<?= intval($editor['id']) ?>"><?= $editor['name'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
        <div>
            <label for="orderfilter">Ordre:</label>
            <select name="orderfilter">
                <option value="alphabeticalasc">Alphabétique (croissant)</option>
                <option value="alphabeticaldesc">Alphabétique (décroissant)</option>
                <option value="creationdateasc">Date d'ajout (croissant)</option>
                <option value="creationdatedesc">Date d'ajout (décroissant)</option>
                <option value="releasedateasc">Année de sortie (croissant)</option>
                <option value="releasedatedesc">Année de sortie (décroissant)</option>
            </select>
        </div>
        <button type="submit">Filtrer</button>
        <a href="index.php?p=all" class="reset">Réinitialiser filtre</a>
    </form>
</section>

<section class="letterfilter" >
    <ul>
        <?php foreach(range('A','Z') as $i) : ?>
            <li><a href="index.php?p=all&genrefilter=<?= $genreFilter ?>&platformfilter=<?= $platformFilter ?>&letterfilter=<?= $i ?>"><?= $i ?></a></li>
            <?php if($i != "Z"): ?>
                <li><?= "-" ?></li>
            <?php endif ?>
        <?php endforeach ?>
    </ul>
</section>

<?php if (empty($games)): ?>
    <p class="searchresult">Nous n'avons rien trouvé avec ces paramètres</p>
<?php else: ?>
    <table id="allgametable">
        <thead>
                <tr>
                    <th>Jeux</th>
                    <th>Plateformes:</th>
                    <th>Genres:</th>
                    <th>Année de parution:</th>
                </tr>
        </thead>
        <tbody>

        </tbody>   
    </table>
<?php endif ?>

<section id="pagingnavbar" class="paging">

</section>