<?php $editController = new EditController() ?>

<?php $toEditGameId = $_GET['id'] ?>

<?php $toEditGame = $editController->getGame($_GET['id']) ?>
<!-- Lancement de la fonction d'édition de jeu -->
<?php if(!empty($_POST)): ?>
    <?= $editController->editGame($_POST) ?>
<?php endif ?>

<section class='add'>
    <h2>Edition d'un jeu</h2>
    <form action="index.php?p=editg&id=<?= $toEditGameId ?>" name="edit" method="POST" enctype="multipart/form-data">
        <ul>
            <li>
                <input name="gameid" type="hidden" value="<?= intval($toEditGameId) ?>">
                <label for="gametitle">Titre du jeu:</label>
                <input name="gametitle" type='text' id="gametitle" onblur="checkForm(this)" value="<?= $toEditGame['name'] ?>">
            </li>  
            <?php $developpers = $editController->getDevs() ?>
            <li>
                <p class="hidden errormsg">Vous devez obligatoirement choisir un developpeur</p>
                <label for="dev">Developpeur:</label>
                <select name="dev" onchange="checkSelect(this)">
                    <option value="0">--Choisissez un Developpeur--</option>
                    <?php foreach ($developpers as $developper):?>
                        <option id="<?= intval($developper['id']) ?>" value="<?= intval($developper['id']) ?>"
                        <?php if($toEditGame['dev_id'] == $developper['id']) echo "selected"; ?>><?= $developper['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <?php $editors = $editController->getEditors() ?>
            <li>
                <p class="hidden errormsg">Vous devez obligatoirement choisir un editeur</p>
                <label for="editor">Editeur:</label>
                <select name="editor">
                    <option value="0">--Choisissez un Editeur--</option>
                    <?php foreach ($editors as $editor):?>
                        <option id="<?= intval($editor['id']) ?>" value="<?= intval($editor['id']) ?>"
                        <?php if($toEditGame['editor_id'] == $editor['id']) echo "selected"; ?>><?= $editor['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li> 
            <li>
                <label for="releasedate">Année de parution</label>
                <input type="text" id="releasedate" name="releasedate" maxlength="4" onblur="checkForm(this)" value="<?= $toEditGame['released_at'] ?>">
            </li>

            <?php $platforms = $editController->getPlatforms() ?>
            <?php $toEditGamePlatforms = $editController->getToEditGamePlatforms($toEditGameId) ?>
            <?php $toEditGameGenres = $editController->getToEditGameGenres($toEditGameId) ?>
            
            <label for="platform1">Plateformes:</label>
            <?php $gamePlatformCount = 0 ?>
            <?php for ($i=1; $i <= 6; $i++): ?>
                <li>  
                    <select name="platform<?= $i ?>" onchange="checkSelect(this)">
                    <option value="0">--Choisissez une plateforme--</option>
                        <?php foreach ($platforms as $platform):?>
                            <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"
                                <?php if (array_key_exists($gamePlatformCount, $toEditGamePlatforms)): ?>
                                    <?php if($platform['id'] == $toEditGamePlatforms[$gamePlatformCount]['id']): ?>
                                        <?php echo "selected" ?>
                                    <?php endif ?>
                                <?php endif ?>>
                                <?= $platform['name'] ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </li>
                <?php $gamePlatformCount++ ?>
            <?php endfor?> 

            <?php $genres = $editController->getGenres() ?>
            <label for="genre1">Genres:</label>
            <?php $gameGenreCount = 0 ?>
            <?php for ($j=1; $j <= 3; $j++): ?> 
                <li >
                    <select name="genre<?= $j ?>">
                        <option value="0">--Choisissez un genre--</option>
                        <?php foreach ($genres as $genre):?>
                            <option id="<?= intval($genre['id']) ?>" value="<?= intval($genre['id']) ?>"
                            <?php if (array_key_exists($gameGenreCount , $toEditGameGenres)): ?>
                                <?php if($genre['id'] == $toEditGameGenres[$gameGenreCount]['id']): ?>
                                    <?php echo "selected" ?>
                                <?php endif ?>
                            <?php endif ?>>
                            <?= $genre['name'] ?></option>
                        <?php endforeach ?>
                    </select>
                </li>
                <?php $gameGenreCount++ ?>
            <?php endfor?> 
            <li>
                <label for='description'>Description:</label>
                <textarea name='description' cols="20" rows="15"><?= $toEditGame['description'] ?></textarea>
            </li>
            <li>
                <label for="picture">Photo du jeu:</label>
                <img src="public/img/games/<?= $toEditGame['image'] ?>" class='imgpreview'>
                <input type="file" id="picture" name="picture" accept=".jpg,.png" onchange="imagePreview(event)">
            </li>
        </ul>
        <button type="submit" id="addBtn" >Enregistrer</button>
    </form>
</section>