<?php $editController = new EditController() ?>

<?php $toEditGameId = $_GET['id'] ?>

<?php $toEditGame = $editController->getGame($_GET['id']) ?>
<!-- Lancement de la fonction d'édition de jeu -->
<?php if(!empty($_POST)): ?>
    <?= $editController->editGame($_POST) ?>
<?php endif ?>

<section class='add'>
    <h2>Edition d'un jeu</h2>
    <form action="index.php?p=editg&id=<?= $toEditGameId ?>" name="edit" method="POST" enctype="multipart/form-data">
        <ul>
            <li>
                <input name="gameid" type="hidden" value="<?= intval($toEditGameId) ?>">
                <label for="gametitle">Titre du jeu:</label>
                <input name="gametitle" type='text' id="gametitle" onblur="checkForm(this)" value="<?= $toEditGame['name'] ?>">
            </li>  
            <?php $developpers = $editController->getDevs() ?>
            <li>
                <p class="hidden errormsg">Vous devez obligatoirement choisir un developpeur</p>
                <label for="dev">Developpeur:</label>
                <select name="dev" onchange="checkSelect(this)">
                    <option value="0">--Choisissez un Developpeur--</option>
                    <?php foreach ($developpers as $developper):?>
                        <option id="<?= intval($developper['id']) ?>" value="<?= intval($developper['id']) ?>"
                        <?php if($toEditGame['dev_id'] == $developper['id']) echo "selected"; ?>><?= $developper['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <?php $editors = $editController->getEditors() ?>
            <li>
                <p class="hidden errormsg">Vous devez obligatoirement choisir un editeur</p>
                <label for="editor">Editeur:</label>
                <select name="editor">
                    <option value="0">--Choisissez un Editeur--</option>
                    <?php foreach ($editors as $editor):?>
                        <option id="<?= intval($editor['id']) ?>" value="<?= intval($editor['id']) ?>"
                        <?php if($toEditGame['editor_id'] == $editor['id']) echo "selected"; ?>><?= $editor['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li> 
            <li>
                <label for="releasedate">Année de parution</label>
                <input type="text" id="releasedate" name="releasedate" maxlength="4" onblur="checkForm(this)" value="<?= $toEditGame['released_at'] ?>">
            </li>

            <?php $platforms = $editController->getPlatforms() ?>
            <?php $toEditGamePlatforms = $editController->getToEditGamePlatforms($toEditGameId) ?>
            <?php $toEditGameGenres = $editController->getToEditGameGenres($toEditGameId) ?>
            
            <li>
                <label for="platform1">Plateformes:</label>
                <select name="platform1" onchange="checkSelect(this)">
                <option value="0">--Choisissez une plateforme--</option>
                    <?php foreach ($platforms as $platform):?>
                        <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"
                            <?php if (array_key_exists(0, $toEditGamePlatforms)): ?>
                                <?php if($platform['id'] == $toEditGamePlatforms[0]['id']): ?>
                                    <?php echo "selected" ?>
                                <?php endif ?>
                            <?php endif ?>>
                            <?= $platform['name'] ?>
                        </option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="platform2">
                <select name="platform2" onchange="checkSelect(this)">
                    <option value="0">--Choisissez une plateforme--</option>
                    <?php foreach ($platforms as $platform):?>
                        <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"
                            <?php if (array_key_exists(1, $toEditGamePlatforms)): ?>
                                <?php if($platform['id'] == $toEditGamePlatforms[1]['id']): ?>
                                    <?php echo "selected" ?>
                                <?php endif ?>
                            <?php endif ?>>
                            <?= $platform['name'] ?>
                        </option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="platform3">
                             
                <select name="platform3" onchange="checkSelect(this)">
                <option value="0">--Choisissez une plateforme--</option>
                    <?php foreach ($platforms as $platform):?>
                        <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"
                            <?php if (array_key_exists(2, $toEditGamePlatforms)): ?>
                                <?php if($platform['id'] == $toEditGamePlatforms[2]['id']): ?>
                                    <?php echo "selected" ?>
                                <?php endif ?>
                            <?php endif ?>>
                            <?= $platform['name'] ?>
                        </option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="platform4">
                
                <select name="platform4" onchange="checkSelect(this)">
                    <option value="0">--Choisissez une plateforme--</option>
                    <?php foreach ($platforms as $platform):?>
                        <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"
                            <?php if (array_key_exists(3, $toEditGamePlatforms)): ?>
                                <?php if($platform['id'] == $toEditGamePlatforms[3]['id']): ?>
                                    <?php echo "selected" ?>
                                <?php endif ?>
                            <?php endif ?>>
                            <?= $platform['name'] ?>
                        </option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="platform5">
                           
                <select name="platform5" onchange="checkSelect(this)">
                    <option value="0">--Choisissez une plateforme--</option>
                    <?php foreach ($platforms as $platform):?>
                        <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"
                            <?php if (array_key_exists(4, $toEditGamePlatforms)): ?>
                                <?php if($platform['id'] == $toEditGamePlatforms[4]['id']): ?>
                                    <?php echo "selected" ?>
                                <?php endif ?>
                            <?php endif ?>>
                            <?= $platform['name'] ?>
                        </option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="platform6">
                
                <select name="platform6" onchange="checkSelect(this)">
                    <option value="0">--Choisissez une plateforme--</option>
                    <?php foreach ($platforms as $platform):?>
                        <option id="<?= intval($platform['id']) ?>" value="<?= intval($platform['id']) ?>"
                            <?php if (array_key_exists(5, $toEditGamePlatforms)): ?>
                                <?php if($platform['id'] == $toEditGamePlatforms[5]['id']): ?>
                                    <?php echo "selected" ?>
                                <?php endif ?>
                            <?php endif ?>>
                            <?= $platform['name'] ?>
                        </option>
                    <?php endforeach ?>
                </select>
            </li>
            <?php $genres = $editController->getGenres() ?>
            <li >
                <label for="genre1">Genres:</label>
                <select name="genre1">
                    <option value="0">--Choisissez un genre--</option>
                    <?php foreach ($genres as $genre):?>
                        <option id="<?= intval($genre['id']) ?>" value="<?= intval($genre['id']) ?>"
                        <?php if (array_key_exists(0 , $toEditGameGenres)): ?>
                            <?php if($genre['id'] == $toEditGameGenres[0]['id']): ?>
                                <?php echo "selected" ?>
                            <?php endif ?>
                        <?php endif ?>>
                        <?= $genre['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="genre2">
                <select name="genre2">
                <option value="0">--Choisissez un genre--</option>
                    <?php foreach ($genres as $genre):?>
                        <option id="<?= intval($genre['id']) ?>" value="<?= intval($genre['id']) ?>"
                        <?php if (array_key_exists(1 , $toEditGameGenres)): ?>
                            <?php if($genre['id'] == $toEditGameGenres[1]['id']): ?>
                                <?php echo "selected" ?>
                                <?php endif ?>
                        <?php endif ?>>
                        <?= $genre['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li id="genre3">
                <select name="genre3">
                <option value="0">--Choisissez un genre--</option>
                    <?php foreach ($genres as $genre):?>
                        <option id="<?= intval($genre['id']) ?>" value="<?= intval($genre['id']) ?>"
                        <?php if (array_key_exists(2 , $toEditGameGenres)): ?>
                            <?php if($genre['id'] == $toEditGameGenres[2]['id']): ?>
                                <?php echo "selected" ?>
                                <?php endif ?>
                        <?php endif ?>>
                        <?= $genre['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li>
                <label for='description'>Description:</label>
                <textarea name='description' cols="20" rows="15"><?= $toEditGame['description'] ?></textarea>
            </li>
            <li>
                <label for="picture">Photo du jeu:</label>
                <input type="file" id="picture" name="picture" accept=".jpg,.png">
            </li>
        </ul>
        <button type="submit" id="addBtn" >Enregistrer</button>
    </form>
</section>