<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title><?= $title ?></title>
        <link href="https://fonts.googleapis.com/css?family=Play:400,700|Titillium+Web:400,700" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
        crossorigin="anonymous">
        <link rel="stylesheet" href="public/css/normalize.css"/>
        <link rel="stylesheet" href="public/css/style.css">
        <link rel="shortcut icon" href="public/img/favicon.ico" type="image/x-icon">
    </head>
    <body>
        <?php $session = new LoginController() ?>
        <?php $isAuthenticated = $session->checkAuthentication() ?>
        <header>
            <h1><i class="fas fa-gamepad"></i>archives du jeux-video</h1>
            <nav>
                <a href="index.php?p=home">Accueil</a>
                <a href="index.php?p=all">Tous les jeux</a>
                <?php if (!$isAuthenticated): ?>
                    <a href="index.php?p=register">S'enregistrer</a>
                <?php elseif ($session->isAdmin()): ?>
                    <a href="index.php?p=add">Ajouter un jeu</a>
                    <a href="index.php?p=admin">Gestion</a>
                <?php else: ?>
                    <a href="index.php?p=add">Ajouter un jeu</a>
                <?php endif?>
            </nav>
        </header>
        <main>
            <section class="forms">
                <!-- si les identifiant et mdp son envoyé on crée la session -->
                <?php if (isset($_POST['login']) && isset($_POST['loginpswrd'])): ?>
                    <?php $session->getSession() ?>
                <?php endif ?>
                <!-- si l'utilisateur n'est pas authentifié on affiche le formulaire de connexion-->
                <?php if (!$isAuthenticated): ?>
                    <form action="" name="loginform" class="loginform" method="POST">
                        <label for="login">Login:</label>
                        <input type="text" name="login">
                        <label for="loginpswrd">Mot-de-passe:</label>
                        <input type="password" name="loginpswrd">
                        <button type="submit">Connexion</button>
                    </form>
                <?php else:?>  
                    <div id="usernfo">
                        <div>
                            <img src="public/img/users/<?= $session->showUserImage() ?>">
                        </div>
                        <div>
                            <p><?= $session->showName() ?></p> 
                            <a href="index.php?p=usernfo">Afficher le profil</a>
                            <a href="index.php?p=deco">Deconnexion</a>
                        </div>
                    </div>
                <?php endif?>       
                <form action='index.php?p=all' class="search" method='POST'>
                    <label for="search">Rechercher un jeu:</label>
                    <input type="text" name="search">
                    <button type="submit">Recherche</button>
                </form>
            </section>
            <?php include $page.'.phtml' ?>
        </main>
        <footer>
            <nav>
            <a href="index.php?p=home">Accueil</a>
                <a href="index.php?p=all">Tous les jeux</a>
                <!-- Si l'utilisateur n'est pas authentifié on affiche le lien vers la page d'enregistrement -->
                <?php if (!$isAuthenticated): ?>
                    <a href="index.php?p=register">S'enregistrer</a>
                <!-- si l'utilisateur est admin on affiche le lien vers la page de gestion admin -->
                <?php elseif ($session->isAdmin()): ?>
                    <!--  et le lien vers al page d'ajout de jeu -->
                    <a href="index.php?p=add">Ajouter un jeu</a>
                    <a href="index.php?p=admin">Gestion</a>
                <?php else: ?>
                <!-- sinon on affiche juste le lien vers la page d'ajout de jeu -->
                    <a href="index.php?p=add">Ajouter un jeu</a>
                <?php endif?>
            </nav>
        </footer>
        <script src="public/js/main.js"></script>
        <script>
            let passedArray = <?= json_encode($toPassList) ?>
        </script>
        <script src="public/js/ajax.js"></script>
        
    </body>
</html>